version: "3.7"
services:
  client:
    build:
      context: client
    ports:
      - 4100:4100
  server:
    build:
      context: server
    environment:
      NODE_ENV: "test"
    ports:
      - 3000:3000
    command: >
      sh -c "wget -q https://raw.githubusercontent.com/eficode/wait-for/master/wait-for -O wait-for && chmod +x wait-for &&
            ./wait-for db:3306 -- npm start"
  db:
    image: mysql:5
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./db/init.sql:/db/init.sql
      - mysql_db:/var/lib/mysql
    command: --init-file /db/init.sql
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: hydra
    ports:
      - 8081:8080
    volumes:
      - ./adminer/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      - ./adminer/adminer.css:/tmp/adminer.css
    command: >
      sh -c "cp -f /tmp/adminer.css /var/www/html/adminer.css &&
            php -S [::]:8080 -t /var/www/html"
volumes:
  mysql_db:
